name: duck_attack
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flame: ^1.34.0
  flutter_riverpod: ^3.2.0
  flame_audio: ^2.11.12
  flutter_native_splash: ^2.4.7
  shared_preferences: ^2.5.4
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  image: ^4.7.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/sprites/
    - assets/images/sprites/grandma/
    - assets/images/sprites/bread/
    - assets/images/sprites/duck/
    - assets/images/sprites/duck/walk/

    - assets/config.yaml
    - assets/images/sprites/sprites.yaml
    - assets/about.txt

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/logo_padded.png"
  android_12:
    image: "assets/images/logo_padded.png"
    color: "#FFFFFF"
